version: 1.0.{build}
image: Visual Studio 2022
configuration: Release

init:
- pwsh: if(test-path -LiteralPath ./ci.build.init.ps1){. ./ci.build.init.ps1}

before_build:
  - choco install dotnet-sdk --version 8.0.100
  - dotnet restore

build:
  project: SayedHa.Commands.sln
  publish_core_console: true
  verbosity: normal

after_build:
  - dotnet pack SayedHa.Commands/SayedHa.Commands.csproj

artifacts:
 - path: '**\nupkg\*.nupkg'
